### ISSUE TITLE
Feature: ability to customize output via templates

### ISSUE THREAD

**Issue by moltar** [Dashlane/dbt-invoke#7]
It'd be nice to be able to customize the output template to set the defaults.

Right now the output looks like:

```yml
version: 2
models:
- name: users
  description: ''
  columns:
  - name: user_id
    description: ''
  - name: created_at
    description: ''
```

But I'd like it to be (to match our org style):

```yml
version: 2
models:
  - name: users

    description: |
      Description

    columns:

    - name: user_id
      description: |
        Description
      tests:
        - not_null

    - name: created_at
      description: |
        Description
      tests:
        - not_null
```

Maybe a project-level Jinja macro could be used?
